#!/bin/sh
IMAGE="__IMAGE__"
NAME="firefox-${USER}"
DATA="${HOME}/.config/mozilla-docker"
OPTS=(
  -v "${DATA}:/data/.mozilla" \
  -v "${HOME}/.config/gtk-3.0/settings.ini:/data/.config/gtk-3.0/settings.ini:ro" \
  -v "${HOME}/Downloads:/data/Downloads" \
)

if [ "$(docker inspect -f {{.State.Running}} ${NAME} 2> /dev/null)" == "true" ]; then
  exec docker exec ${NAME} firefox "$@"
else
  mkdir -p "${DATA}"
  eval exec $(docker inspect -f {{.Config.Labels.RUN}} ${IMAGE}) '"$@"'
fi
