WUZZ_BIN = https://github.com/asciimoo/wuzz/releases/download/v0.3.0/wuzz_linux_amd64
WUZZ_SHA256 = a956844dba446810d0910c8e8b77f2315e3b93a8e82cc45c7bcd273185477e17
VARS += WUZZ_BIN WUZZ_SHA256

include ../config.mk ../default.mk
