WUZZ_BIN = https://github.com/asciimoo/wuzz/releases/download/v0.4.0/wuzz_linux_amd64
WUZZ_SHA256 = 5a1443e07a5a9b9bb813804290e87fdd27b544f4fe00ef95fe3b64e7b56459ec
VARS += WUZZ_BIN WUZZ_SHA256

include ../config.mk ../default.mk
