#!/bin/sh
IMAGE="__IMAGE__"
NAME="clementine-${USER}"
DATA="${HOME}/.config/Clementine"
OPTS=(
  -v /media:/media:ro \
  -v "${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}:ro" \
  -v "${DATA}:/data/.config/Clementine:rw" \
  -v "${HOME}/Downloads:/data/Downloads:rw" \
  -v "${HOME}/Library:/data/Library:ro" \
  -v "${HOME}/Music:/data/Music:ro" \
  -v "${HOME}/Public:/data/Public:ro" \
  -v "${HOME}/Videos:/data/Videos:ro" \
)

if [ "$(docker inspect -f {{.State.Running}} ${NAME} 2> /dev/null)" == "true" ]; then
  exec docker exec ${NAME} clementine "$@"
else
  mkdir -p "${DATA}"
  eval exec $(docker inspect -f {{.Config.Labels.RUN}} ${IMAGE}) '"$@"'
fi
