#!/bin/bash
IMAGE="__IMAGE__"
NAME="chrome-${USER}"
DATA="${HOME}/.config/google-chrome-docker"
OPTS=(
  --privileged \
  -v /dev/dri:/dev/dri:ro \
  -v /dev/snd:/dev/snd:ro \
  -v "${DATA}:/data/.config/google-chrome" \
  -v "${HOME}/Downloads:/data/Downloads" \
)

if [ "$(docker inspect -f {{.State.Running}} ${NAME} 2> /dev/null)" == "true" ]; then
  exec docker exec ${NAME} google-chrome "$@"
else
  mkdir -p "${DATA}"
  eval exec $(docker inspect -f {{.Config.Labels.RUN}} ${IMAGE}) '"$@"'
fi
