#!/bin/bash -u
# Configuration file

NAME=$2
RELEASE=$3
REPOS=(fedora fedora-updates)
GPGCHECK=1
PACKAGES=(
  bash \
  bind-utils \
  bzip2 \
  coreutils \
  curl \
  dnf \
  dnf-plugins-core \
  file \
  findutils \
  gnupg2 \
  hostname \
  icu \
  iproute \
  iputils \
  less \
  make \
  nmap-ncat \
  openssh-clients \
  openssl \
  passwd \
  patch \
  perl \
  procps-ng \
  psmisc \
  python \
  python3 \
  rpm \
  rsync \
  socat \
  sqlite \
  sudo \
  systemd \
  tar \
  util-linux \
  vim-minimal \
  which \
  xz \
  zip \
)

XUSER=container
XHOME=/data
XUID=65000
XGID=65000

DOCKER_IMAGE=${1}/${2}:${3}
DOCKER_ENV="LANG=en_US.UTF-8 LC_COLLATE=POSIX container=docker \
XUSER=${XUSER} XHOME=${XHOME} XUID=${XUID} XGID=${XGID}"

CACHEDIR=/var/cache/dnf
CHROOT=/var/tmp/${NAME}-${RELEASE}-$(arch)
REPOSDIR=${SCRIPTDIR}/yum.repos.d
