#!/bin/bash
DATA="${HOME}/.config/mpv"
mkdir -p "${DATA}"

exec docker run -u $UID:$GID --rm --privileged --cap-drop=ALL \
-v /etc/group:/etc/group:ro \
-v /etc/localtime:/etc/localtime:ro \
-v /etc/machine-id:/etc/machine-id:ro \
-v /etc/passwd:/etc/passwd:ro \
-v /dev:/dev:rw \
-v /run/user/${UID}:/run/user/${UID}:ro \
-v /tmp/.X11-unix:/tmp/.X11-unix:ro -e DISPLAY="unix${DISPLAY}" \
-v "${HOME}/Downloads:${HOME}/Downloads:ro" \
-v "${HOME}/Music:${HOME}/Music:ro" \
-v "${HOME}/Public:${HOME}/Public:ro" \
-v "${HOME}/Videos:${HOME}/Videos:ro" \
-v "${DATA}:/data/.config/mpv:rw" \
-w "$(pwd)" "__IMAGE__" "$@"
