#!/bin/sh
IMAGE="__IMAGE__"
NAME="mpv-${USER}"
DATA="${HOME}/.config/mpv"
OPTS=(
  --privileged \
  -v /dev/dri:/dev/dri:ro \
  -v /dev/snd:/dev/snd:ro \
  -v /media:/media:ro \
  -v "${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}:rw" \
  -v "${DATA}:/data/.config/mpv:rw" \
  -v "${HOME}/Downloads:${HOME}/Downloads:ro" \
  -v "${HOME}/Library:${HOME}/Library:ro" \
  -v "${HOME}/Music:${HOME}/Music:ro" \
  -v "${HOME}/Public:${HOME}/Public:ro" \
  -v "${HOME}/Videos:${HOME}/Videos:ro" \
  -w "$(pwd)" \
)

if [ "$(docker inspect -f {{.State.Running}} ${NAME} 2> /dev/null)" == "true" ]; then
  exec docker exec ${NAME} mpv "$@"
else
  mkdir -p "${DATA}"
  eval exec $(docker inspect -f {{.Config.Labels.RUN}} ${IMAGE}) '"$@"'
fi
