#!/bin/bash -eu
. /etc/sysconfig/containers/pwnie/*
NAME=${NAME}-${RANDOM}
OPT1=''
while [ $# -ge 1 ]; do
  case "$1" in
  :*) IMAGE=$(echo ${IMAGE} | sed -E 's/:\w*$//')${1};;
  -*) OPT1="${OPT1} ${1}";;
   *) break;;
  esac
  shift
done
eval exec $(docker inspect -f {{.Config.Labels.RUN}} ${IMAGE}) '"$@"'
