PLEX_VERSION = 1.7.5.4035-313f93718
PLEX_SHA256 = 89b8585e561046a8422d520ebcdae784f5dc3c895aac8d313c435cc6b58795b8
PLEX_RPM = https://downloads.plex.tv/plex-media-server/$(PLEX_VERSION)/plexmediaserver-$(PLEX_VERSION).$(ARCH).rpm
VARS += PLEX_SHA256 PLEX_RPM PLEX_VERSION

include ../config.mk ../default.mk
