PLEX_VERSION = 1.9.4.4325-1bf240a65
PLEX_SHA256 = adf891b14447948b11e0b65d6f11d4420442e7d6c7620b4afea577c648d6f87f
PLEX_RPM = https://downloads.plex.tv/plex-media-server/$(PLEX_VERSION)/plexmediaserver-$(PLEX_VERSION).x86_64.rpm
VARS += PLEX_SHA256 PLEX_RPM PLEX_VERSION

include ../config.mk ../default.mk
