PLEX_VERSION = 1.8.4.4249-3497d6779
PLEX_SHA256 = ca3db297f4dbc73a5a405ac032ff250e5df97b84da6dcac55165b13e6445ca80
PLEX_RPM = https://downloads.plex.tv/plex-media-server/$(PLEX_VERSION)/plexmediaserver-$(PLEX_VERSION).x86_64.rpm
VARS += PLEX_SHA256 PLEX_RPM PLEX_VERSION

include ../config.mk ../default.mk
