#!/bin/bash -eu
INAME=$(echo ${IMAGE} | awk -F/ '{print $(NF)}' | awk -F: '{print $1}')

# Destinations for artifacts
HOST_SYSTEMD=${HOST}/etc/systemd/system
ENVROOT=${HOST}/etc/sysconfig/containers
ENVFILE=${ENVROOT}/${INAME}/${NAME}

# Defaults for volumes
: ${CONFDIR:=/etc/containers/${INAME}/${NAME}}
: ${DATADIR:=/var/containers/${INAME}/${NAME}}
: ${LOGDIR:=}

# Expand variables in a file
function parse_file() {
eval echo "\"$(cat <<EOF
$(<$1)
EOF
)\""
}

# Initialize a volume directory
function mkvol() {
  mkdir -pvm 0750 "$1"
  chmod -c 0750 "$1"
  chown -c "$XUSER": "$1"
}

# List names of installed instances
function find_instances() {
  find $(dirname ${ENVFILE}) -type f -not -name '*~' -printf "%f\n" 2> /dev/null
}
