#!/bin/bash -eu
INAME=$(echo ${IMAGE} | awk -F/ '{print $(NF)}' | awk -F: '{print $1}')

# Destinations for artifacts
SYSTEMD=${HOST}/etc/systemd/system
ENVROOT=${HOST}/etc/sysconfig/containers
ENVFILE=${ENVROOT}/${NAME}

# Defaults for volumes
: ${CONFDIR:=/etc/containers/${NAME}}
: ${DATADIR:=/var/containers/${NAME}}
: ${LOGDIR:=}

# Expand variables in a file
function parse_file() {
eval echo "\"$(cat <<EOF
$(<$1)
EOF
)\""
}

# Initialize a volume directory
function mkvol() {
  mkdir -pvm 0750 "$1"
  chmod -c 0750 "$1"
  chown -c "$XUSER": "$1"
}

# List names of installed instances ignoring tags
function find_instances() {
  grep -Elr "^IMAGE=$(echo ${IMAGE} | sed -r 's/:\w*$//')(:\w*)?$" \
  ${ENVROOT}/*[!~] | xargs -r basename
}
