#!/bin/bash -eu
if [ -f /artifacts/atomic-uninstall.sh ]; then
  . /artifacts/atomic-uninstall.sh
fi

if [ $# -ne 0 ] && [[ "$1" =~ ^(erase|force|purge|remove)$ ]]; then
  [ -n "${CONFDIR-}" ] && rm -rfv "${HOST}/${CONFDIR}"
  [ -n "${DATADIR-}" ] && rm -rfv "${HOST}/${DATADIR}"
  [ -n "${LOGDIR-}"  ] && rm -rfv "${HOST}/${LOGDIR}"
fi
