#!/bin/bash -eu
. /etc/atomic-install
pushd /artifacts > /dev/null

# Source and move the env file!
if [ -f ${ENVFILE} ]; then
  . ${ENVFILE}
  mv -v ${ENVFILE}{,~}
fi

# Delete obsoleted installed files...
if [ $(find_instances | wc -l) -eq 0 ]; then
  find . -maxdepth 1 -regex '.+\.\(service\|timer\)\(\.d\)?$' \
    -exec rm -rfv "${HOST_SYSTEMD}/{}" \;
  find . -maxdepth 2 -mindepth 2 -wholename './profile.d/*' \
    -exec rm -rfv "${HOST_ETC}/{}" \;
  find . -maxdepth 2 -mindepth 2 -wholename './*bin/*' \
    -exec rm -rfv "${HOST_USR}/{}" \;
fi

# Execute extension...
if [ -f atomic-uninstall.sh ]; then
  . atomic-uninstall.sh
fi

# Delete everything if requested...
if [ $# -ge 1 ] && [[ "$1" =~ ^(erase|purge)$ ]]; then
  rm -f ${ENVFILE}{,~} 2> /dev/null || :
  rmdir $(dirname ${ENVFILE}) 2> /dev/null || :
  [ -n "${CONFDIR}" ] && rm -rfv "${HOST}/${CONFDIR}" || :
  [ -n "${DATADIR}" ] && rm -rfv "${HOST}/${DATADIR}" || :
  [ -n "${LOGDIR}"  ] && rm -rfv "${HOST}/${LOGDIR}"  || :
fi

popd > /dev/null
exit 0
