#!/bin/bash
IMAGE="__IMAGE__"
NAME="hexchat-${USER}"
DATA="${HOME}/.config/hexchat"
OPTS=(-v "${DATA}:/data/.config/hexchat")

if [ "$(docker inspect -f {{.State.Running}} ${NAME} 2> /dev/null)" == "true" ]; then
  exec docker exec ${NAME} hexchat --existing "$@"
else
  mkdir -p "${DATA}"
  docker rm -fv ${NAME} &> /dev/null
  eval exec $(docker inspect -f {{.Config.Labels.RUN}} ${IMAGE}) '"$@"'
fi
