#!/bin/bash
IMAGE="__IMAGE__"
NAME="skype-${USER}"
DATA="${HOME}/.Skype"
OPTS=(
  -v "${DATA}:/data/.Skype" \
  -v "${HOME}/Downloads:/data/Downloads" \
)

if [ "$(docker inspect -f {{.State.Running}} ${NAME} 2> /dev/null)" == "true" ]; then
  exec docker exec ${NAME} skype "$@"
else
  mkdir -p "${DATA}"
  eval exec $(docker inspect -f {{.Config.Labels.RUN}} ${IMAGE}) '"$@"'
fi
