#!/bin/sh
IMAGE="__IMAGE__"
NAME="libreoffice-${USER}"
DATA="${HOME}/.config/libreoffice"
OPTS=(
  -v "${DATA}:/data/.config/libreoffice" \
  -v "${HOME}/Documents:/data/Documents" \
  -v "${HOME}/Downloads:/data/Downloads" \
  -v "${HOME}/Public:/data/Public" \
  -v "${HOME}/Templates:/data/Templates" \
)
ARGV=()

while [ $# -gt 0 ]; do
  x=$1
  if [[ "$x" == "file://"* ]]; then
    x=${x:7}
    x=$(printf '%b' "${x//%/\\x}")
  fi
  if [ -d "$x" ]; then
    wdir=$(realpath "$x")
    OPTS+=(-v "${wdir}:/data/${wdir//\//_}")
  elif [ -f "$x" ]; then
    if [[ "$x" =~ "$HOME"/(Documents|Downloads|Public|Templates)/.* ]]; then
      ARGV+=("$(realpath -s --relative-base="$HOME" "$x")")
    else
      wdir=$(dirname "$(realpath "$x")")
      dest=${wdir//\//_}
      OPTS+=(-v "${wdir}:/data/${dest}")
      ARGV+=("${dest}/$(basename "$x")")
    fi
  else
    ARGV+=("$1")
  fi
  shift
done

if [ "$(docker inspect -f {{.State.Running}} ${NAME} 2> /dev/null)" == "true" ]; then
  exec docker exec ${NAME} libreoffice "${ARGV[@]}"
else
  mkdir -p "${DATA}"
  eval exec $(docker inspect -f {{.Config.Labels.RUN}} ${IMAGE}) '"${ARGV[@]}"'
fi
