#!/bin/bash
IMAGE="__IMAGE__"
NAME="electrum-${USER}"
DATA="${HOME}/.electrum"
OPTS=(
  -v "${DATA}:/data/.electrum" \
  -v "${HOME}/Downloads:/data/Downloads" \
)

if [ "$(docker inspect -f {{.State.Running}} ${NAME} 2> /dev/null)" == "true" ]; then
  exec docker exec ${NAME} electrum "$@"
else
  mkdir -p "${DATA}"
  docker rm -fv ${NAME} &> /dev/null
  eval exec $(docker inspect -f {{.Config.Labels.RUN}} ${IMAGE}) '"$@"'
fi
