#!/bin/bash
IMAGE="__IMAGE__"
NAME="keepassx-${USER}"
DATA="${HOME}/.config/keepassx"
OPTS=(
  -v /media:/media:rw \
  -v "${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}:rw" \
  -v "${DATA}:/data/.config/keepassx:rw" \
  -v "${HOME}/Documents:${HOME}/Documents:rw" \
  -v "${HOME}/Downloads:${HOME}/Downloads:rw" \
  -v "${HOME}/Works:${HOME}/Works:rw" \
  -w "$(pwd)" \
)

if [ "$(docker inspect -f {{.State.Running}} ${NAME} 2> /dev/null)" == "true" ]; then
  exec docker exec ${NAME} keepassx "$@"
else
  mkdir -p "${DATA}"
  docker rm -fv ${NAME} &> /dev/null
  eval exec $(docker inspect -f {{.Config.Labels.RUN}} ${IMAGE}) '"$@"'
fi
