#!/bin/bash
PWD=$(git rev-parse --show-toplevel 2> /dev/null)
: ${PWD:=$(pwd)}

exec docker run -it --rm --net=host --security-opt=label:disable \
-u $UID:$GID -v "$PWD:$PWD" -w "$PWD" "__IMAGE__" "$@"
